### PR TITLE
Add a .python-version file with "3.8"

### PR DESCRIPTION
**Pull request by themilkman**
As discussed on discord, this shouldn't have any negative impact :)

### CODE REVIEW

**Comment by themilkman** [comment]
I do not really know if this is a valid test, but this command (I think I got it from you)

```python
[p.split('/')[1] for p in sublime.find_resources("dependencies.json")]
```
results in:
```python
['Package Control']
```
only.

With an .python-version override which results with the following in the console:
```
reloading plugin Terminal.Terminal
```

But as I said I cannot say if this is sufficient.

**Comment by braver** [comment]
I would've just merged this, now you make me worry 😅 A lot of this package is still deeply ancient, and I don't have access to anything other than a Mac. So, I could go with just shipping this and we'll just see if anyone reports an issue. YOLO 🤣  @FichteFoll let me know what you think though.

**Comment by FichteFoll** [comment]
`winreg` is part of the stdlib (otherwise this package would have needed to specify this as a dependency before as well).

I do have a Windows installation lying around still but I only use it very rarely. I don't *expect* anything to break by going to 3.8, though, so imo merging this should be fine. If there is an issue (and people end up reporting it), rolling it back would be trivial, too.

**Comment by braver** [comment]
well here goes nothing

**Pull request merged**
